const STATUS={todo:"Başlamadım",learning:"Öğreniyorum",done:"Öğrendim"},STATUS_ORDER={todo:0,learning:1,done:2};
const starterTopics=[{title:"JavaScript temellerini sağlamlaştır",category:"JavaScript",status:"learning",notes:"Fonksiyonlar, array/object, scope ve hata yönetimi.",resource:""},{title:"HTTP istek ve cevaplarını anla",category:"Backend",status:"todo",notes:"Method, header, body ve status code kavramlarını incele.",resource:""},{title:"IP, port, DNS ve TCP temelleri",category:"Ağ",status:"todo",notes:"Bir adresi açarken ağda gerçekleşen adımları açıklayabil.",resource:""},{title:"Cookie, session ve yetkilendirme",category:"Web Güvenliği",status:"todo",notes:"Authentication ile authorization farkını öğren.",resource:""}].map((t,i)=>({...t,id:crypto.randomUUID(),updatedAt:Date.now()-i*1000}));
const DEFAULT_CATEGORIES=["JavaScript","Backend","Ağ","Web Güvenliği","CTI / SOC","Diğer"];
const state={topics:[],categories:[],category:"Tümü",status:"all",query:"",sort:"updatedAt-desc",theme:"dark",page:1,pageSize:10,draggedId:null},$=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),dialog=$("#topic-dialog");let isEditorDirty=false;
const storageGet=key=>new Promise(resolve=>{if(globalThis.chrome?.storage?.local)return chrome.storage.local.get(key,resolve);const keys=Array.isArray(key)?key:[key],result={};keys.forEach(k=>{const value=localStorage.getItem(k);if(value!==null)result[k]=JSON.parse(value)});resolve(result)});
const storageSet=value=>new Promise(resolve=>{if(globalThis.chrome?.storage?.local)return chrome.storage.local.set(value,resolve);Object.entries(value).forEach(([k,v])=>localStorage.setItem(k,JSON.stringify(v)));resolve()});
async function init(){const saved=await storageGet(["topics","preferences","categories"]);state.topics=(Array.isArray(saved.topics)?saved.topics:starterTopics).map(t=>({...t,status:["practiced","mastered"].includes(t.status)?"done":t.status}));state.categories=Array.isArray(saved.categories)?saved.categories:[...DEFAULT_CATEGORIES];state.topics.forEach(t=>{if(!state.categories.includes(t.category))state.categories.push(t.category)});Object.assign(state,saved.preferences||{});if(!saved.topics||!saved.categories)await save();bindEvents();bindCategoryEvents();bindEnhancements();bindListEnhancements();applyTheme();render()}
function bindEvents(){$("#open-form").onclick=()=>openForm();$("#empty-add").onclick=()=>openForm();$("#close-dialog").onclick=()=>dialog.close();$("#cancel-dialog").onclick=()=>dialog.close();$("#topic-form").onsubmit=saveForm;$("#delete-topic").onclick=deleteCurrent;$("#notes").oninput=e=>{$("#note-count").textContent=e.target.value.length;markDirty()};["#title","#category","#resource"].forEach(s=>$(s).addEventListener("input",markDirty));$("#search").oninput=e=>{state.query=e.target.value.toLocaleLowerCase("tr");renderTable()};$("#category-select").onchange=e=>{state.category=e.target.value;renderTable();savePreferences()};$("#status-filter").onchange=e=>{state.status=e.target.value;renderTable();savePreferences()};$("#sort-select").onchange=e=>{state.sort=e.target.value;renderTable();savePreferences()};$("#clear-filters").onclick=()=>{state.category="Tümü";state.status="all";state.query="";$("#search").value="";syncControls();renderTable();savePreferences()};$$('[data-sort]').forEach(b=>b.onclick=()=>toggleSort(b.dataset.sort));document.addEventListener("keydown",e=>{if(e.key.toLowerCase()==="n"&&!dialog.open&&!/input|textarea|select/i.test(e.target.tagName)){e.preventDefault();openForm()}})}
function openForm(topic=null){$("#topic-form").reset();$("#edit-id").value=topic?.id||"";$("#dialog-title").textContent=topic?"Konuyu düzenle":"Yeni konu";$("#delete-topic").classList.toggle("hidden",!topic);$("#category-manager").classList.remove("hidden","open");$("#toggle-category-manager").setAttribute("aria-expanded","false");renderEditorCategories(topic?.category);if(topic){$("#title").value=topic.title;$("#notes").value=topic.notes||"";$("#resource").value=topic.resource||""}dialog.dataset.status=topic?.status||"todo";renderEditorStatus();$("#notes").placeholder="Notlarını buraya yaz…\n\n• Konuyu kendi cümlelerinle açıkla.\n• Önemli noktaları ve örnekleri ekle.\n• Anlamadığın yerleri not al.\n• Bir sonraki adımını belirle.";$("#note-count").textContent=$("#notes").value.length;$("#save-hint").textContent=topic?"Düzenlemeye hazır":"Yeni çalışma sayfası";isEditorDirty=false;dialog.showModal();$("#title").focus()}
function markDirty(){isEditorDirty=true;$("#save-hint").textContent="Kaydedilmemiş değişiklikler"}
function renderEditorStatus(){const container=$("#editor-status-buttons");container.replaceChildren();Object.entries(STATUS).forEach(([value,label])=>{const button=document.createElement("button");button.type="button";button.className=`status-button status-${value}${dialog.dataset.status===value?" active":""}`;button.textContent=label;button.onclick=()=>{dialog.dataset.status=value;renderEditorStatus();markDirty()};container.append(button)})}
async function saveForm(e){e.preventDefault();const id=$("#edit-id").value,topic={id:id||crypto.randomUUID(),title:$("#title").value.trim(),category:$("#category").value,status:dialog.dataset.status||"todo",notes:$("#notes").value.trim(),resource:$("#resource").value.trim(),updatedAt:Date.now()};state.topics=id?state.topics.map(t=>t.id===id?topic:t):[topic,...state.topics];await save();isEditorDirty=false;$("#save-hint").textContent="Kaydedildi";dialog.close();render()}
async function deleteCurrent(){const id=$("#edit-id").value;if(!id)return;const accepted=await askConfirmation({title:"Konuyu sil?",message:"Bu konu ve içindeki bütün notlar kalıcı olarak silinecek.",accept:"Evet, sil",danger:true});if(!accepted)return;state.topics=state.topics.filter(t=>t.id!==id);await save();isEditorDirty=false;dialog.close();render()}
async function updateStatus(topic,status){topic.status=status;topic.updatedAt=Date.now();await save();render()}
const save=()=>storageSet({topics:state.topics,categories:state.categories}),savePreferences=()=>storageSet({preferences:{category:state.category,status:state.status,sort:state.sort,theme:state.theme}});
function render(){renderStats();renderCategories();syncControls();renderTable()}
function renderStats(){const total=state.topics.length,active=state.topics.filter(t=>t.status==="learning").length,done=state.topics.filter(t=>t.status==="done").length,p=total?Math.round(done/total*100):0;$("#nav-total").textContent=total;$("#nav-active").textContent=active;$("#nav-done").textContent=done;$("#progress-value").textContent=`${p}%`;$("#progress-bar").style.width=`${p}%`;$("#done-count").textContent=`${done} öğrenildi`;$("#remaining-count").textContent=`${total-done} kaldı`}
function renderCategories(){const select=$("#category-select"),current=state.category,cats=["Tümü",...state.categories];select.replaceChildren(...cats.map(c=>new Option(c,c)));if(cats.includes(current))select.value=current;else state.category="Tümü"}
function syncControls(){$("#category-select").value=state.category;$("#status-filter").value=state.status;$("#sort-select").value=state.sort}
function getVisible(){const [key,direction]=state.sort.split("-");return state.topics.filter(t=>(state.category==="Tümü"||t.category===state.category)&&(state.status==="all"||t.status===state.status)&&`${t.title} ${t.notes}`.toLocaleLowerCase("tr").includes(state.query)).sort((a,b)=>{let av=a[key],bv=b[key];if(key==="status"){av=STATUS_ORDER[av];bv=STATUS_ORDER[bv]}const result=typeof av==="string"?av.localeCompare(bv,"tr"):av-bv;return direction==="desc"?-result:result})}
function renderTable(){const visible=getVisible(),noTopics=state.topics.length===0,noResults=!noTopics&&visible.length===0;$("#result-count").textContent=visible.length;$("#empty-state").classList.toggle("hidden",!noTopics);$("#no-results").classList.toggle("hidden",!noResults);$("#table-view").classList.toggle("hidden",noTopics||noResults);$("#topic-table-body").replaceChildren(...visible.map((topic,index)=>createRow(topic,index)))}
function bindCategoryEvents(){$("#toggle-category-manager").onclick=()=>{const manager=$("#category-manager"),open=manager.classList.toggle("open");$("#toggle-category-manager").setAttribute("aria-expanded",String(open));if(open)setTimeout(()=>$("#new-category").focus(),180)};$("#add-category").onclick=addCategory;$("#new-category").oninput=e=>e.target.setCustomValidity("");$("#new-category").onkeydown=e=>{if(e.key==="Enter"){e.preventDefault();addCategory()}}}
function renderEditorCategories(selected){const select=$("#category");select.replaceChildren(...state.categories.map(c=>new Option(c,c)));if(selected&&state.categories.includes(selected))select.value=selected;renderCategoryManager()}
function renderCategoryManager(){const list=$("#category-list");$("#category-count").textContent=`${state.categories.length} alan`;list.replaceChildren(...state.categories.map(category=>{const row=document.createElement("div");row.className="category-item";const usage=state.topics.filter(t=>t.category===category).length;row.innerHTML=`<div class="category-info"><i class="category-color"></i><span class="category-name"></span><span class="category-usage"></span></div><button type="button" ${usage?"disabled":""} aria-label="${category} alanını sil">×</button>`;row.querySelector(".category-name").textContent=category;row.querySelector(".category-usage").textContent=usage?`${usage} konu`:"boş";row.querySelector("button").onclick=()=>removeCategory(category);return row}))}
async function addCategory(){const input=$("#new-category"),name=input.value.trim();if(!name)return;if(state.categories.some(c=>c.toLocaleLowerCase("tr")===name.toLocaleLowerCase("tr"))){input.setCustomValidity("Bu alan zaten var.");input.reportValidity();return}input.setCustomValidity("");state.categories.push(name);input.value="";await save();renderEditorCategories(name);renderCategories();markDirty()}
async function removeCategory(category){if(state.topics.some(t=>t.category===category))return;const accepted=await askConfirmation({title:"Alanı sil?",message:`“${category}” alanı listeden kaldırılacak.`,accept:"Alanı sil",danger:true});if(!accepted)return;state.categories=state.categories.filter(c=>c!==category);await save();renderEditorCategories();renderCategories();markDirty()}
function bindEnhancements(){$("#close-dialog").onclick=requestEditorClose;$("#cancel-dialog").onclick=requestEditorClose;$("#theme-toggle").onclick=()=>{state.theme=state.theme==="pink"?"dark":"pink";applyTheme();savePreferences()};const expandBtn=$("#expand-tab");if(expandBtn){const isPopup=window.outerWidth<800&&window.outerHeight<700;if(!isPopup){expandBtn.classList.add("hidden")}else{expandBtn.onclick=()=>{if(globalThis.chrome?.tabs){chrome.tabs.create({url:chrome.runtime.getURL("index.html")})}else{window.open(chrome.runtime.getURL("index.html"),"_blank")}}}}}
async function requestEditorClose(){if(!isEditorDirty){dialog.close();return}const accepted=await askConfirmation({title:"Değişikliklerden vazgeç?",message:"Kaydetmediğin düzenlemeler silinecek.",accept:"Vazgeç",danger:false});if(accepted){isEditorDirty=false;dialog.close()}}
function applyTheme(){document.body.dataset.theme=state.theme;const button=$("#theme-toggle");button.querySelector("b").textContent=state.theme==="pink"?"Koyu tema":"Pembe tema";button.classList.toggle("active",state.theme==="pink")}
function askConfirmation({title,message,accept,danger}){return new Promise(resolve=>{const modal=$("#confirm-dialog"),acceptButton=$("#confirm-accept");$("#confirm-title").textContent=title;$("#confirm-message").textContent=message;acceptButton.textContent=accept;acceptButton.className=danger?"confirm-danger":"confirm-primary";const finish=value=>{modal.close();resolve(value)};$("#confirm-cancel").onclick=()=>finish(false);acceptButton.onclick=()=>finish(true);modal.oncancel=e=>{e.preventDefault();finish(false)};modal.showModal()})}
function bindListEnhancements(){const reset=()=>{state.page=1;renderTable()};$("#search").oninput=e=>{state.query=e.target.value.toLocaleLowerCase("tr");reset()};$("#category-select").onchange=e=>{state.category=e.target.value;reset();savePreferences()};$("#status-filter").onchange=e=>{state.status=e.target.value;reset();savePreferences()};$("#clear-filters").onclick=()=>{state.category="Tümü";state.status="all";state.query="";state.page=1;$("#search").value="";syncControls();renderTable();savePreferences()}}
function getVisible(){return state.topics.filter(t=>(state.category==="Tümü"||t.category===state.category)&&(state.status==="all"||t.status===state.status)&&`${t.title} ${t.notes}`.toLocaleLowerCase("tr").includes(state.query))}
function renderTable(){const visible=getVisible(),totalPages=Math.max(1,Math.ceil(visible.length/state.pageSize));state.page=Math.min(state.page,totalPages);const start=(state.page-1)*state.pageSize,pageTopics=visible.slice(start,start+state.pageSize),noTopics=state.topics.length===0,noResults=!noTopics&&visible.length===0;$("#result-count").textContent=visible.length;$("#empty-state").classList.toggle("hidden",!noTopics);$("#no-results").classList.toggle("hidden",!noResults);$("#table-view").classList.toggle("hidden",noTopics||noResults);$("#topic-table-body").replaceChildren(...pageTopics.map((topic,index)=>createRow(topic,start+index)));renderPagination(visible.length,totalPages)}
function createRow(topic,index){const tr=document.createElement("tr");tr.dataset.id=topic.id;tr.draggable=true;tr.innerHTML=`<td class="drag-cell"><button class="drag-handle" type="button" aria-label="${topic.title} konusunu taşı">⠿</button></td><td class="row-number"></td><td class="table-title"></td><td><span class="category-pill"></span></td><td></td><td class="table-notes"></td><td class="table-date"></td><td><button class="row-action">Düzenle</button></td>`;tr.children[1].textContent=String(index+1).padStart(2,"0");tr.children[2].textContent=topic.title;tr.querySelector(".category-pill").textContent=topic.category;tr.children[4].append(statusButtons(topic));tr.querySelector(".table-notes").textContent=topic.notes||"—";tr.querySelector(".table-date").textContent=new Date(topic.updatedAt).toLocaleDateString("tr-TR");tr.onclick=()=>openForm(topic);tr.querySelector(".row-action").onclick=e=>{e.stopPropagation();openForm(topic)};tr.querySelector(".drag-handle").onclick=e=>e.stopPropagation();tr.ondragstart=e=>{state.draggedId=topic.id;tr.classList.add("dragging");e.dataTransfer.effectAllowed="move"};tr.ondragend=()=>{state.draggedId=null;tr.classList.remove("dragging");$$("tr.drag-over").forEach(row=>row.classList.remove("drag-over"))};tr.ondragover=e=>{e.preventDefault();if(state.draggedId!==topic.id)tr.classList.add("drag-over")};tr.ondragleave=()=>tr.classList.remove("drag-over");tr.ondrop=e=>{e.preventDefault();e.stopPropagation();tr.classList.remove("drag-over");moveTopic(state.draggedId,topic.id)};return tr}
async function moveTopic(sourceId,targetId){if(!sourceId||sourceId===targetId)return;const sourceIndex=state.topics.findIndex(t=>t.id===sourceId),targetIndex=state.topics.findIndex(t=>t.id===targetId);if(sourceIndex<0||targetIndex<0)return;const [moved]=state.topics.splice(sourceIndex,1);const adjustedTarget=state.topics.findIndex(t=>t.id===targetId);state.topics.splice(adjustedTarget,0,moved);await save();renderTable()}
function renderPagination(total,totalPages){const nav=$("#pagination");nav.classList.toggle("hidden",total<=state.pageSize);if(total<=state.pageSize){nav.replaceChildren();return}const buttons=[];const previous=document.createElement("button");previous.textContent="← Önceki";previous.disabled=state.page===1;previous.onclick=()=>changePage(state.page-1);buttons.push(previous);for(let page=1;page<=totalPages;page++){const button=document.createElement("button");button.textContent=page;button.className=page===state.page?"active":"";button.setAttribute("aria-label",`${page}. sayfa`);button.onclick=()=>changePage(page);buttons.push(button)}const next=document.createElement("button");next.textContent="Sonraki →";next.disabled=state.page===totalPages;next.onclick=()=>changePage(state.page+1);buttons.push(next);nav.replaceChildren(...buttons)}
function changePage(page){state.page=page;renderTable();$("#table-view").scrollIntoView({behavior:"smooth",block:"start"})}
init();
